export const ACCESS_TYPE_SUPERADMIN = "SUPERADMIN";
export const ACCESS_TYPE_BUSINESS_ADMIN = "BUSINESS_ADMIN";
export const ACCESS_TYPE_BUSINESS_USER = "BUSINESS_USER";
export const ACCESS_TYPE_BUSINESS_CLIENT = "BUSINESS_CLIENT";
